config/routes.rb
Journal::Application.routes.draw do
  devise_for :users, :skip => :registrations
  resources :entries
  root to: "entries#index"

  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  has_many :entries     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.where :user => current_user
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    params_with_user = entry_params.merge(:user_id => current_user.id)

    @entry = Entry.new(params_with_user) 

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:physical_location, :place, :mood, :took_place_at, :positive_activity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
= form_for @entry do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :physical_location
    = f.text_field :physical_location
  .field
    = f.label :place
    = f.text_field :place
  .field
    = f.label :mood
    = f.text_field :mood
  .field
    = f.label :took_place_at
    = f.datetime_select :took_place_at
  .field
    = f.label :positive_activity
    = f.text_field :positive_activity
  .actions
    = f.submit 'Save'

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', entries_path

app/views/entries/index.html.haml
%h1 Listing entries

%table
  %tr
    %th User email  
    %th Physical location
    %th Place
    %th Mood
    %th Took place at
    %th Positive activity
    %th
    %th
    %th

  - @entries.each do |entry|
    %tr
      %td= entry.user.email
      %td= entry.physical_location
      %td= entry.place
      %td= entry.mood
      %td= entry.took_place_at
      %td= entry.positive_activity
      %td= link_to 'Show', entry
      %td= link_to 'Edit', edit_entry_path(entry)
      %td= link_to 'Destroy', entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_entry_path

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', entries_path

app/views/entries/show.html.haml
%p#notice= notice

%p
  %b Physical location:
  = @entry.physical_location
%p
  %b Place:
  = @entry.place
%p
  %b Mood:
  = @entry.mood
%p
  %b Took place at:
  = @entry.took_place_at
%p
  %b Positive activity:
  = @entry.positive_activity

= link_to 'Edit', edit_entry_path(@entry)
\|
= link_to 'Back', entries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>